name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: Project/youtube-player-ios-example

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Show workspace content
        run: |
          pwd
          ls -al

      - name: Run UI Tests
        run: |
          xcodebuild test \
            -workspace youtube-player-ios-example.xcworkspace \
            -scheme youtube-player-ios-example \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=16.2" \
            -derivedDataPath build

      - name: Upload test result bundle (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xcode-result-bundle
          path: /var/folders/**/ResultBundle_*.xcresult
          retention-days: 7