# .github/workflows/ci.yml
name: UI Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: echo "Simulate XCTest"

      - name: Upload dummy result
        uses: actions/upload-artifact@v2
        with:
          name: sample
          path: README.md

