name: iOS UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies

    - name: Build for testing
      run: |
        xcodebuild test \
          -project youtube-ios-player-helper.xcodeproj \
          -scheme "youtube-player-ios-example" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          -enableCodeCoverage YES

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: XCTestResults
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test

